name: CI

on:
  - pull_request
  - push

jobs:
  unit-tests:
    strategy:
      matrix:
        operating-system:
          - ubuntu-latest
        php-version:
          - 7.4
          - 8.0
    name: unit-tests on php-${{ matrix.php-version }} - ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Pull Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: imagick
          coverage: xdebug

      - name: Install composer dependencies
        run: composer update --no-ansi --no-interaction --no-progress

      - name: Run unit tests
        run: vendor/bin/phpunit tests
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: my-docker-hub-namespace/my-docker-hub-repository
          tag_with_ref: true
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: my-org/my-repo/my-image
          tag_with_ref: true
